### ISSUE TITLE
Add support to use custom repo URL for Klipper and Moonraker in China

### ISSUE THREAD

**Issue by sjqlwy** [Arksine/moonraker#470]
### Is your feature request related to a problem? Please describe

Due to network instability, Chinese users are preferred to use github mirrors for Klipper and Moonraker update, which will show **invalid** or **dirty** in web front. Although kiauh is available for manual update, this method is not that elegant.  Will moonraker support custom update_manager like others? Thx.

### Describe the solution you'd like

```yaml
[update_manager Custom_Moonraker]
type: git_repo
path: ~/moonraker
origin: https://ghproxy.com/https://github.com/arksine/moonraker.git
env: ~/moonraker-env/bin/python
requirements: scripts/moonraker-requirements.txt
install_script: scripts/install-moonraker.sh
managed_services: moonraker
```
